---
name: Build - macOS

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "vcpkg.json"
  merge_group:
  push:
    paths:
      - "src/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "vcpkg.json"
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        buildtype: [macos-release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install macOS dependencies
        run: brew install ccache autoconf automake libtool

      - name: Setup cached CMake environment
        uses: ./.github/actions/setup-cmake-build-env
        with:
          compiler-cache-key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          vcpkg-cache-suffix: ${{ matrix.os }}-${{ matrix.buildtype }}

      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: crystalserver-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
