---
name: Lua-format
on:
  pull_request_target:
    paths:
      - "data*/**"
  push:
    paths:
      - "data*/**"

permissions:
  contents: write

jobs:
  lua-formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout PR head (using PAT)
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref:       ${{ github.event.pull_request.head.ref }}
          token:     ${{ secrets.PAT_TOKEN }}

      - name: Run stylua (format)
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          version: latest
          args: .

      - name: Commit formatted changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Lua code format - (Stylua)"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}